dogbr = {
    "affenpinscher": "аффенпинчер",
    "african": "африканская борзая",
    "airedale": "эрдельтерьер",
    "akita": "акита",
    "appenzeller": "аппенцеллер",
    "australian": "австралийская овчарка",
    "basenji": "басенджи",
    "beagle": "бигль",
    "bluetick": "блютек",
    "borzoi": "русская борзая",
    "bouvier": "бувье",
    "boxer": "боксер",
    "brabancon": "брабансон",
    "briard": "бриар",
    "buhund": "бухунд",
    "bulldog": "бульдог",
    "bullterrier": "бультерьер",
    "cattledog": "кеттлдог",
    "cavapoo": "кавапу",
    "chihuahua": "чихуахуа",
    "chow": "чау-чау",
    "clumber": "кламбер",
    "cockapoo": "кокапу",
    "collie": "колли",
    "coonhound": "кунхаунд",
    "corgi": "корги",
    "cotondetulear": "котон де тулеар",
    "dachshund": "такса",
    "dalmatian": "далматин",
    "dane": "датский дог",
    "deerhound": "шотландский дирхаунд",
    "dhole": "дхол",
    "dingo": "динго",
    "doberman": "доберман",
    "elkhound": "лосиный хаунд",
    "entlebucher": "энтльбухер",
    "eskimo": "эскимосская лайка",
    "finnish": "финский шпиц",
    "frise": "болоньез",
    "germanshepherd": "немецкая овчарка",
    "greyhound": "грейхаунд",
    "groenendael": "грюнендаль",
    "havanese": "гаванез",
    "hound": "хаунд",
    "husky": "хаски",
    "keeshond": "кеесхонд",
    "kelpie": "келпи",
    "komondor": "комондор",
    "kuvasz": "кувас",
    "labradoodle": "лабрадудль",
    "labrador": "лабрадор",
    "leonberg": "леонбергер",
    "lhasa": "лхаса апсо",
    "malamute": "маламут",
    "malinois": "малинуа",
    "maltese": "мальтийская болонка",
    "mastiff": "мастиф",
    "mexicanhairless": "мексиканская бесшерстная собака",
    "mix": "метис",
    "mountain": "горная собака",
    "newfoundland": "ньюфаундленд",
    "otterhound": "оттерхаунд",
    "ovcharka": "овчарка",
    "papillon": "папильон",
    "pekinese": "пекинес",
    "pembroke": "пемброк",
    "pinscher": "пинчер",
    "pitbull": "питбуль",
    "pointer": "пойнтер",
    "pomeranian": "померанский шпиц",
    "poodle": "пудель",
    "pug": "мопс",
    "puggle": "паггл",
    "pyrenees": "пиренейская горная собака",
    "redbone": "рэдбон",
    "retriever": "ретривер",
    "ridgeback": "родезийский риджбек",
    "rottweiler": "ротвейлер",
    "saluki": "салюки",
    "samoyed": "самоед",
    "schipperke": "шипперке",
    "schnauzer": "шнауцер",
    "segugio": "сегужо",
    "setter": "сеттер",
    "sharpei": "шарпей",
    "sheepdog": "шотландская овчарка",
    "shiba": "сиба-ину",
    "shihtzu": "шитцу",
    "spaniel": "спаниель",
    "spitz": "шпиц",
    "springer": "английский спрингер-спаниель",
    "stbernard": "сент-бернар",
    "terrier": "терьер",
    "tervuren": "тервюрен",
    "vizsla": "выжла",
    "waterdog": "ватердог",
    "weimaraner": "веймаранер",
    "whippet": "виппет",
    "wolfhound": "ирландский вольфхаунд",
}
